name: CI

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m json.tool 'it-IT/it.json' > /dev/null
          python -m json.tool 'it-IT/module.json' > /dev/null

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build artifact
        run: |
          zip -r it-IT.zip it-IT -x ".*"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: it-IT
          path: it-IT.zip
